[package]
name = "terra-mars"
version = "1.0.0"
authors = ["Spike Spiegel <spikeonmars@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw2 = "0.8"
cw20 = "0.8"
cw20-base = { version = "0.8", features = ["library"] }

terra-cosmwasm = "2.2.0"
terraswap = "2.4.0"

cosmwasm-std = { version = "0.16.0" }

schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = "1.0.20"
