[package]
name = "mars"
version = "0.1.0"
authors = ["Spike Spiegel <spikeonmars@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = "0.7"
cw20-base = { version = "0.7", features = ["library"] }

terra-cosmwasm = "2.1.0"
cosmwasm-bignumber = "2.1.1"
terraswap = "2.3.0"

cosmwasm-std = { version = "0.15.0", features = ["iterator"] }
cosmwasm-storage = { version = "0.15.0", features = ["iterator"] }

schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = "1.0.20"
